spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:h2:tcp://localhost/~/ezgoingfork
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jvm:
    compiler: -parameters

  jpa:
    hibernate:
      ddl-auto : create
    properties:
      hibernate:
        format_sql: true

logging.level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace

springboot:
  jwt:
    secret : QUJDREVGSElKS0xNTk9QUVJTVFVWV1hZWjEyMzQ1Njc4OTA=

